"""
Django settings for fitness project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Directory containing `manage.py` (project root)
BASE_DIR = Path(__file__).resolve().parent.parent

# Local-only convenience: load `.env` while running locally.
# In production (Railway), env vars are already injected, so this does not override them.
load_dotenv(BASE_DIR / ".env")

def _is_railway_runtime() -> bool:
    return any(
        os.getenv(var)
        for var in (
            "RAILWAY_ENVIRONMENT",
            "RAILWAY_PROJECT_ID",
            "RAILWAY_SERVICE_ID",
            "RAILWAY_PUBLIC_DOMAIN",
        )
    )


default_env = "production" if _is_railway_runtime() else "local"
DJANGO_ENV = os.getenv("DJANGO_ENV", default_env).lower()

# Keep the Django settings entrypoint small and delegate to environment-specific modules.
if DJANGO_ENV == "production":
    from .config.production import *  # noqa: F403,F401
else:
    from .config.local import *  # noqa: F403,F401
