# Generated by Django 6.0.3 on 2026-03-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('mobility', 'Mobility'), ('core', 'Core'), ('cardio', 'Cardio'), ('rehab', 'Rehab / Prevention')], default='strength', max_length=30)),
                ('primary_muscle', models.CharField(choices=[('full_body', 'Full body'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cable', 'Cable'), ('band', 'Resistance band'), ('bodyweight', 'Bodyweight'), ('cardio_machine', 'Cardio machine'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=30)),
                ('contraindications', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority substitutions are preferred.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_from', to='exercises.exercise')),
                ('to_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_to', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Exercise substitution',
                'verbose_name_plural': 'Exercise substitutions',
                'ordering': ['-active', '-priority', 'from_exercise_id', 'to_exercise_id'],
                'constraints': [models.UniqueConstraint(fields=('from_exercise', 'to_exercise'), name='unique_exercise_substitution_pair')],
            },
        ),
    ]
