# Generated by Django 6.0.3 on 2026-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'Gyakorlat', 'verbose_name_plural': 'Gyakorlatok'},
        ),
        migrations.AlterModelOptions(
            name='exercisesubstitution',
            options={'ordering': ['-active', '-priority', 'from_exercise_id', 'to_exercise_id'], 'verbose_name': 'Gyakorlat helyettesítés', 'verbose_name_plural': 'Gyakorlat helyettesítések'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Erő'), ('hypertrophy', 'Izomtömeg'), ('mobility', 'Mobilitás'), ('core', 'Törzs'), ('cardio', 'Kardió'), ('rehab', 'Rehabilitáció / megelőzés')], default='strength', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Kezdő'), ('intermediate', 'Középhaladó'), ('advanced', 'Haladó')], db_index=True, default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Rúd'), ('dumbbell', 'Súlyzó'), ('kettlebell', 'Kettlebell'), ('machine', 'Gép'), ('cable', 'Kábel'), ('band', 'Ellenállási szalag'), ('bodyweight', 'Saját testsúly'), ('cardio_machine', 'Kardió gép'), ('other', 'Egyéb')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('full_body', 'Teljes test'), ('chest', 'Mell'), ('back', 'Hát'), ('shoulders', 'Váll'), ('biceps', 'Bicepsz'), ('triceps', 'Tricepsz'), ('quadriceps', 'Combizom'), ('hamstrings', 'Comhajlítók'), ('glutes', 'Farizom'), ('calves', 'Vádli'), ('core', 'Törzs'), ('other', 'Egyéb')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercisesubstitution',
            name='priority',
            field=models.IntegerField(default=0, help_text='Magasabb prioritású helyettesítések előnyben.'),
        ),
    ]
