# Generated by Django 6.0.3 on 2026-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-active', 'name'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='exercisesubstitution',
            options={'ordering': ['-active', '-priority', 'from_exercise_id', 'to_exercise_id'], 'verbose_name': 'Exercise substitution', 'verbose_name_plural': 'Exercise substitutions'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('mobility', 'Mobility'), ('core', 'Core'), ('cardio', 'Cardio'), ('rehab', 'Rehab / prevention')], default='strength', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cable', 'Cable'), ('band', 'Resistance band'), ('bodyweight', 'Bodyweight'), ('cardio_machine', 'Cardio machine'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle',
            field=models.CharField(choices=[('full_body', 'Full body'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('quadriceps', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('core', 'Core'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercisesubstitution',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher-priority substitutions take precedence.'),
        ),
    ]
