# Generated by Django 6.0.3 on 2026-03-20 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('gym_one_day', 'Gym (One Day)')], default='gym_one_day', max_length=40)),
                ('goal', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('fat_loss', 'Fat Loss'), ('general_fitness', 'General Fitness'), ('rehab_prevention', 'Rehab / Prevention')], default='general_fitness', max_length=30)),
                ('available_time', models.PositiveSmallIntegerField(default=60, help_text='Available time for the workout in minutes.')),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('soreness_level', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(db_index=True, default=False)),
                ('generated_context_json', models.JSONField(blank=True, default=dict, help_text='Debug/audit context used by the planner engine (keep sanitized).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User that created the plan (trainer/staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Workout plan',
                'verbose_name_plural': 'Workout plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, help_text='Subjective difficulty rating (e.g., 1-10).', null=True)),
                ('energy_after', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('pain_flag', models.BooleanField(default=False, help_text='Whether the member reported pain that should trigger adjustments.')),
                ('feedback_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout feedback',
                'verbose_name_plural': 'Workout feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Display/execution order within the plan.')),
                ('block_type', models.CharField(choices=[('warmup', 'Warmup'), ('main_work', 'Main work'), ('cooldown', 'Cooldown')], default='main_work', max_length=20)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(blank=True, default='', help_text="Rep prescription (e.g., '8-12', '10', 'time:45s').", max_length=30)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('tempo', models.CharField(blank=True, default='', help_text="Tempo prescription (e.g., '2-0-2').", max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_usages', to='exercises.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout exercise',
                'verbose_name_plural': 'Workout exercises',
                'ordering': ['workout_plan_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('workout_plan', 'order'), name='unique_exercise_order_within_plan')],
            },
        ),
    ]
