# Generated by Django 6.0.3 on 2026-03-27 19:15

import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='exercise_slugs',
            field=models.JSONField(blank=True, default=workouts.models._empty_exercise_slugs, help_text='Ordered exercise slugs in this plan (for repetition queries and quick counts).'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='generated_plan_json',
            field=models.JSONField(blank=True, default=workouts.models._empty_plan_json, help_text='Full validated workout proposal (warmup/main/accessory/cooldown). Source of truth when set.'),
        ),
    ]
