# Generated by Django 6.0.3 on 2026-04-16 17:06

import django.db.models.deletion
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutplan_json_plan_and_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['workout_plan_id', 'order'], 'verbose_name': 'Edzés gyakorlat', 'verbose_name_plural': 'Edzés gyakorlatok'},
        ),
        migrations.AlterModelOptions(
            name='workoutfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Edzés visszajelzés', 'verbose_name_plural': 'Edzés visszajelzések'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Edzésterv', 'verbose_name_plural': 'Edzéstervek'},
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='block_type',
            field=models.CharField(choices=[('warmup', 'Bemelegítés'), ('main_work', 'Fő munka'), ('cooldown', 'Levezetés')], default='main_work', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Megjelenítési / végrehajtási sorrend a terven belül.'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.CharField(blank=True, default='', help_text='Ismétlések (pl. „8–12”, „10”, „idő:45 mp”).', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='tempo',
            field=models.CharField(blank=True, default='', help_text='Tempó (pl. „2-0-2”).', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Szubjektív nehézség (pl. 1–10).', null=True),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='energy_after',
            field=models.CharField(choices=[('low', 'Alacsony'), ('medium', 'Közepes'), ('high', 'Magas')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='pain_flag',
            field=models.BooleanField(default=False, help_text='A tag fájdalmat jelzett-e, ami miatt módosítani kell a tervet.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='available_time',
            field=models.PositiveSmallIntegerField(default=60, help_text='Az edzésre fordítható idő percben.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='A tervet létrehozó felhasználó (edző / személyzet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Alacsony'), ('medium', 'Közepes'), ('high', 'Magas')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_slugs',
            field=models.JSONField(blank=True, default=workouts.models._empty_exercise_slugs, help_text='A tervben szereplő gyakorlatok slug-jai sorrendben (ismétlődés és gyors számlálás).'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='generated_context_json',
            field=models.JSONField(blank=True, default=dict, help_text='A tervezőmotor által használt napló / hibakeresési kontextus (csak szűrt adat).'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='generated_plan_json',
            field=models.JSONField(blank=True, default=workouts.models._empty_plan_json, help_text='Teljes, érvényesített edzésjavaslat (bemelegítés / főblokk / kiegészítő / levezetés). Ha ki van töltve, ez az igazság forrása.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(choices=[('strength', 'Erő'), ('hypertrophy', 'Izomtömeg'), ('fat_loss', 'Zsírégetés'), ('general_fitness', 'Általános kondíció'), ('rehab_prevention', 'Rehabilitáció / megelőzés')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='session_type',
            field=models.CharField(choices=[('gym_one_day', 'Konditerem (egy nap)')], default='gym_one_day', max_length=40),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='soreness_level',
            field=models.CharField(choices=[('none', 'Nincs'), ('mild', 'Enyhe'), ('moderate', 'Közepes'), ('severe', 'Erős')], default='none', max_length=15),
        ),
        migrations.CreateModel(
            name='WorkoutPlanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_source', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plan_questions', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workouts.workoutplan')),
            ],
            options={
                'verbose_name': 'Edzésterv kérdés',
                'verbose_name_plural': 'Edzésterv kérdések',
                'ordering': ['-created_at'],
            },
        ),
    ]
