# Generated by Django 6.0.3 on 2026-06-01 18:12

import django.db.models.deletion
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_plan_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['workout_plan_id', 'order'], 'verbose_name': 'Workout exercise', 'verbose_name_plural': 'Workout exercises'},
        ),
        migrations.AlterModelOptions(
            name='workoutfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout feedback', 'verbose_name_plural': 'Workout feedback entries'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout plan', 'verbose_name_plural': 'Workout plans'},
        ),
        migrations.AlterModelOptions(
            name='workoutplanquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout plan question', 'verbose_name_plural': 'Workout plan questions'},
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='block_type',
            field=models.CharField(choices=[('warmup', 'Warm-up'), ('main_work', 'Main work'), ('cooldown', 'Cool-down')], default='main_work', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Display / execution order within the plan.'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.CharField(blank=True, default='', help_text='Reps (e.g. “8–12”, “10”, “time:45 s”).', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='tempo',
            field=models.CharField(blank=True, default='', help_text='Tempo (e.g. “2-0-2”).', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Subjective difficulty (e.g. 1–10).', null=True),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='energy_after',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutfeedback',
            name='pain_flag',
            field=models.BooleanField(default=False, help_text='Whether the member reported pain that should adjust the plan.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='available_time',
            field=models.PositiveSmallIntegerField(default=60, help_text='Available time for the workout in minutes.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the plan (coach / staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_slugs',
            field=models.JSONField(blank=True, default=workouts.models._empty_exercise_slugs, help_text='Slugs of exercises in the plan in order (used for repetition control and fast counting).'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='generated_context_json',
            field=models.JSONField(blank=True, default=dict, help_text='Planner engine log / debug context (filtered data only).'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='generated_plan_json',
            field=models.JSONField(blank=True, default=workouts.models._empty_plan_json, help_text='Full validated workout proposal (warm-up / main / accessory / cool-down). When set, this is the source of truth.'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('fat_loss', 'Fat loss'), ('general_fitness', 'General fitness'), ('rehab_prevention', 'Rehab / prevention')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='session_type',
            field=models.CharField(choices=[('gym_one_day', 'Gym (single day)')], default='gym_one_day', max_length=40),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='soreness_level',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=15),
        ),
    ]
