# Generated by Django 6.0.3 on 2026-03-20 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(default=18, help_text='Member age in years.')),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, help_text='Height in centimeters.', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms.', max_digits=6, null=True)),
                ('training_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('primary_goal', models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('fat_loss', 'Fat Loss'), ('general_fitness', 'General Fitness'), ('rehab_prevention', 'Rehab / Prevention')], default='general_fitness', max_length=30)),
                ('preferred_session_duration', models.PositiveSmallIntegerField(default=60, help_text='Preferred workout duration in minutes (used as a planning hint).')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to the Django auth user for this member.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member profile',
                'verbose_name_plural': 'Member profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('avoid', 'Avoid'), ('limit', 'Limit'), ('modify', 'Modify'), ('note', 'Note')], default='avoid', max_length=20)),
                ('body_area', models.CharField(choices=[('full_body', 'Full body'), ('back', 'Back'), ('chest', 'Chest'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('hips', 'Hips'), ('knees', 'Knees'), ('ankles', 'Ankles'), ('core', 'Core'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Member restriction',
                'verbose_name_plural': 'Member restrictions',
                'ordering': ['-active', '-created_at'],
            },
        ),
    ]
