# Generated by Django 6.0.3 on 2026-04-16 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tag profil', 'verbose_name_plural': 'Tag profilok'},
        ),
        migrations.AlterModelOptions(
            name='memberrestriction',
            options={'ordering': ['-active', '-created_at'], 'verbose_name': 'Tag korlátozás', 'verbose_name_plural': 'Tag korlátozások'},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Megjelenített telefonszám (tag saját fiókja vagy edző által megadva).', max_length=32),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Csak számjegyek (egységes kereséshez); üres, ha nincs telefon.', max_length=32),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, help_text='A tag életkora években.'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Magasság centiméterben.', null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='preferred_session_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Preferált edzésidő percben (tervezési jelzés).'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='primary_goal',
            field=models.CharField(choices=[('strength', 'Erő'), ('hypertrophy', 'Izomtömeg'), ('fat_loss', 'Zsírégetés'), ('general_fitness', 'Általános kondíció'), ('rehab_prevention', 'Rehabilitáció / megelőzés')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='sex',
            field=models.CharField(choices=[('female', 'Nő'), ('male', 'Férfi'), ('unspecified', 'Nincs megadva')], default='unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='training_level',
            field=models.CharField(choices=[('beginner', 'Kezdő'), ('intermediate', 'Középhaladó'), ('advanced', 'Haladó')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Opcionális kapcsolat a tag Django-felhasználójához.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Testsúly kilogrammban.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberrestriction',
            name='body_area',
            field=models.CharField(choices=[('full_body', 'Teljes test'), ('back', 'Hát'), ('chest', 'Mell'), ('shoulders', 'Váll'), ('arms', 'Kar'), ('hips', 'Csípő'), ('knees', 'Térd'), ('ankles', 'Boka'), ('core', 'Törzs'), ('other', 'Egyéb')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('avoid', 'Kerülendő'), ('limit', 'Korlátozás'), ('modify', 'Módosítás'), ('note', 'Megjegyzés')], default='avoid', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='memberprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_normalized__gt', '')), fields=('phone_normalized',), name='members_memberprofile_phone_normalized_nonempty_unique'),
        ),
    ]
