# Generated by Django 6.0.3 on 2026-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_phone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='weekly_workout_frequency',
            field=models.CharField(choices=[('1_2', '1–2 nap'), ('3_4', '3–4 nap'), ('5_7', '5–7 nap')], default='3_4', help_text='Heti edzésszám (becslés).', max_length=10),
        ),
    ]
