# Generated by Django 6.0.3 on 2026-06-01 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_uploadedworkoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymequipment',
            options={'ordering': ['equipment'], 'verbose_name': 'Gym equipment', 'verbose_name_plural': 'Gym equipment'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Member profile', 'verbose_name_plural': 'Member profiles'},
        ),
        migrations.AlterModelOptions(
            name='memberrestriction',
            options={'ordering': ['-active', '-created_at'], 'verbose_name': 'Member restriction', 'verbose_name_plural': 'Member restrictions'},
        ),
        migrations.AlterModelOptions(
            name='uploadedworkoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Uploaded workout plan', 'verbose_name_plural': 'Uploaded workout plans'},
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, help_text='Member age in years.'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters.', null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text="Displayed phone number (member's own account or provided by the coach).", max_length=32),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Digits only (for consistent search); empty when no phone is set.', max_length=32),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='preferred_session_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='Preferred workout duration in minutes (planning signal).'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='primary_goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('fat_loss', 'Fat loss'), ('general_fitness', 'General fitness'), ('rehab_prevention', 'Rehab / prevention')], default='general_fitness', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unspecified', 'Not specified')], default='unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='training_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Optional link to the member's Django user.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='weekly_workout_frequency',
            field=models.CharField(choices=[('1_2', '1–2 days'), ('3_4', '3–4 days'), ('5_7', '5–7 days')], default='3_4', help_text='Weekly workout frequency (estimate).', max_length=10),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in kilograms.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='memberrestriction',
            name='body_area',
            field=models.CharField(choices=[('full_body', 'Full body'), ('back', 'Back'), ('chest', 'Chest'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('hips', 'Hips'), ('knees', 'Knees'), ('ankles', 'Ankles'), ('core', 'Core'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('avoid', 'Avoid'), ('limit', 'Limit'), ('modify', 'Modify'), ('note', 'Note')], default='avoid', max_length=20),
        ),
    ]
